#!/usr/bin/env cs
# Generated by Extended CovScript Compiler
# DO NOT MODIFY
# Date: Tue May 18 18:20:57 2021
struct __ecs_lambda_impl_1__
	var act = null
	function construct(_act)
		this.act := _act
	end
	function call(txt)
		link self = this.call
		act->get_view_by_id("text")->text = txt
	end
end
import ecs
import picasso as ui
import imgui
import imgui_font
var app = ecs.param_new(ui.application, {imgui.window_application(640, 400, "Picasso UI Test")})
var act = app.add_activity(ui.activities.single_page)
act->window->font = imgui.add_font_extend_cn(imgui_font.source_han_sans, 16)
act->add_widget(*app.make_view(ui.widgets.text, "text", {}))
act->add_widget(*app.make_view(ui.widgets.input, "input", {}))
act->get_view_by_id("input")->on_render.add_listener(ecs.init_lambda(global.__ecs_lambda_impl_1__, act))
app.push(act->id)
app.start()

